### ISSUE TITLE
add Linux support

### ISSUE THREAD

**Issue by alexanderadam** [git-time-metric/homebrew-gtm#1]
It seems that the homebrew script always takes the osx binary instead of looking which operating system is actually used.

**Comment by mschenk42** [comment]
I didn't realize that Homebrew has been ported to Linux.  I'll see if we can add support for Linux.  You can get the binary releases for Linux here, https://github.com/git-time-metric/gtm/releases

**Comment by alexanderadam** [comment]
Yes, it was ported at least two years ago.

Awesome, thank you for gtm and the homebrew package. It's really impressive work.

**Comment by mschenk42** [comment]
@alexanderadam Not sure I did this the best way but I think it will work. Can you try this out?
```
brew update
brew install gtmlinux
```

**Comment by alexanderadam** [comment]
Awesome, that seems to work flawlessly! :+1: 

(Although it should be possible to have Linux support covered in the same bottle)

**Comment by alexanderadam** [comment]
maybe something like

```ruby
if OS.mac?
  url "https://github.com/git-time-metric/gtm/releases/download/v1.3.3/gtm.v1.3.3.osx.tar.gz"
  sha256 "5a1a924ade70cd412a0dd84b7607cfad3a07754f8fa14dea2440f182cc5884ba"
elsif OS.linux?
  url "https://github.com/git-time-metric/gtm/releases/download/v1.3.3/gtm.v1.3.3.linux.tar.gz"
  sha256 "0022ccde788ac85f4648338ddfd4bd20cdd8dd9adc0232cc52d453d2f27cdd6f"
end
```
could work as well, if you don't want to maintain two bottles.

I don't know whether this works. I just [saw this in other bottles](https://github.com/jmchilton/homebrew-science-test1/blob/b591c71b75a089edfd0c6e2dcef456f7a8efce41/pcap.rb).

**Comment by mschenk42** [comment]
That worked great.  Thank you.
